// <auto-generated />
namespace SpaConnect.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddDPtoSteps : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddDPtoSteps));
        
        string IMigrationMetadata.Id
        {
            get { return "201809052346086_AddDPtoSteps"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
